version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "PicPay_SqlPass2026!"
      MSSQL_PID: "Developer" # Options: Developer, Express, Standard, Enterprise
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - picpay-network
  

volumes:
  mssql_data:  
  
networks:
  picpay-network:
    name: picpay-network
    driver: bridge